2024-08-23 16:04:15,897 - INFO - Starting
2024-08-23 16:04:15,897 - INFO - Start polling
2024-08-23 16:04:16,036 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:05:20,592 - INFO - Polling stopped
2024-08-23 16:05:20,844 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:05:23,934 - INFO - Starting
2024-08-23 16:05:23,935 - INFO - Start polling
2024-08-23 16:05:24,066 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:06:18,013 - INFO - Polling stopped
2024-08-23 16:06:18,269 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:06:20,897 - INFO - Starting
2024-08-23 16:06:20,897 - INFO - Start polling
2024-08-23 16:06:21,027 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:06:27,480 - INFO - Polling stopped
2024-08-23 16:06:27,742 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:07:16,649 - INFO - Starting
2024-08-23 16:07:16,650 - INFO - Start polling
2024-08-23 16:07:16,791 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:07:24,330 - INFO - Polling stopped
2024-08-23 16:07:24,584 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:08:46,722 - INFO - Start polling
2024-08-23 16:08:46,854 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:09:08,270 - INFO - Polling stopped
2024-08-23 16:09:08,530 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
DEBUG:asyncio:Using proactor: IocpProactor
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:11:29,999 - INFO - Start polling
2024-08-23 16:11:30,144 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:13:52,145 - INFO - Starting
2024-08-23 16:13:52,145 - INFO - Start polling
2024-08-23 16:13:52,274 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:14:28,538 - INFO - Polling stopped
2024-08-23 16:14:28,808 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:14:31,369 - INFO - Starting
2024-08-23 16:14:31,369 - INFO - Start polling
2024-08-23 16:14:31,522 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:15:22,485 - INFO - Polling stopped
2024-08-23 16:15:22,739 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:15:47,714 - INFO - Run_Main
2024-08-23 16:15:47,715 - INFO - Starting
2024-08-23 16:15:47,715 - INFO - Start polling
2024-08-23 16:15:47,871 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:28:53,524 - INFO - Polling stopped
2024-08-23 16:28:53,788 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:28:56,307 - INFO - Run_Main
2024-08-23 16:28:56,307 - INFO - Starting
2024-08-23 16:28:56,307 - INFO - Start polling
2024-08-23 16:28:56,478 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:30:12,577 - INFO - Update id=142968463 is handled. Duration 171 ms by bot id=7510687058
2024-08-23 16:30:13,782 - INFO - Update id=142968464 is not handled. Duration 0 ms by bot id=7510687058
2024-08-23 16:31:41,688 - INFO - Update id=142968465 is not handled. Duration 0 ms by bot id=7510687058
2024-08-23 16:31:43,889 - INFO - Update id=142968466 is handled. Duration 171 ms by bot id=7510687058
2024-08-23 16:31:52,212 - INFO - Update id=142968467 is not handled. Duration 0 ms by bot id=7510687058
2024-08-23 16:31:56,500 - INFO - Polling stopped
2024-08-23 16:31:56,746 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:32:07,920 - INFO - Run_Main
2024-08-23 16:32:07,920 - INFO - Starting
2024-08-23 16:32:07,920 - INFO - Start polling
2024-08-23 16:32:08,095 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:32:24,163 - INFO - Update id=142968468 is handled. Duration 188 ms by bot id=7510687058
2024-08-23 16:32:25,481 - INFO - Update id=142968469 is handled. Duration 77 ms by bot id=7510687058
2024-08-23 16:32:44,922 - INFO - Polling stopped
2024-08-23 16:32:45,168 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:33:06,175 - INFO - Run_Main
2024-08-23 16:33:06,176 - INFO - Starting
2024-08-23 16:33:06,176 - INFO - Start polling
2024-08-23 16:33:06,324 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 16:33:08,266 - INFO - Update id=142968470 is handled. Duration 202 ms by bot id=7510687058
2024-08-23 16:33:10,141 - INFO - Update id=142968471 is handled. Duration 93 ms by bot id=7510687058
2024-08-23 16:33:11,966 - INFO - Update id=142968472 is handled. Duration 0 ms by bot id=7510687058
2024-08-23 17:30:06,621 - INFO - Polling stopped
2024-08-23 17:30:06,875 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 17:30:10,163 - INFO - Run_Main
2024-08-23 17:30:10,164 - INFO - Starting
2024-08-23 17:30:10,164 - INFO - Start polling
2024-08-23 17:30:10,319 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 17:32:14,162 - INFO - Update id=142968473 is not handled. Duration 172 ms by bot id=7510687058
2024-08-23 17:32:14,162 - ERROR - Cause exception while process update id=142968473 by bot id=7510687058
TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 2] Can not write request body for https://api.telegram.org/bot7510687058:AAGuBRCwwoZWhxp54qKaOfD8lXj6F3z93Q8/sendPhoto
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client_reqrep.py", line 637, in write_bytes
    await self.body.write(writer)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\multipart.py", line 993, in write
    await part.write(writer)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\payload.py", line 442, in write
    chunk = await self._iter.__anext__()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\types\input_file.py", line 103, in read
    async with aiofiles.open(self.path, "rb") as f:
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiofiles\base.py", line 98, in __aenter__
    self._obj = await self._coro
                ^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiofiles\threadpool\__init__.py", line 94, in _open
    f = yield from loop.run_in_executor(executor, cb)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.jpeg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\client\session\aiohttp.py", line 181, in make_request
    async with session.post(
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 1353, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client.py", line 684, in _request
    await resp.start(conn)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\client_reqrep.py", line 999, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiohttp\streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 2] Can not write request body for https://api.telegram.org/bot7510687058:AAGuBRCwwoZWhxp54qKaOfD8lXj6F3z93Q8/sendPhoto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\router.py", line 137, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\router.py", line 170, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\router.py", line 137, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\NextCloud\3D_NAS_Code\Courses_Python\Storage_Code\Mentor_Courses\telegram_bot_prototype\main\handlers\user_menu.py", line 14, in start_command
    await message.answer_photo(photo=image)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\client\bot.py", line 488, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\aiogram\client\session\aiohttp.py", line 188, in make_request
    raise TelegramNetworkError(method=method, message=f"{type(e).__name__}: {e}")
aiogram.exceptions.TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 2] Can not write request body for https://api.telegram.org/bot7510687058:AAGuBRCwwoZWhxp54qKaOfD8lXj6F3z93Q8/sendPhoto
2024-08-23 17:32:15,665 - INFO - Update id=142968474 is handled. Duration 140 ms by bot id=7510687058
2024-08-23 17:35:59,385 - INFO - Polling stopped
2024-08-23 17:35:59,642 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 17:36:02,563 - INFO - Run_Main
2024-08-23 17:36:02,564 - INFO - Starting
2024-08-23 17:36:02,564 - INFO - Start polling
2024-08-23 17:36:02,706 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 17:36:19,818 - INFO - Update id=142968475 is handled. Duration 250 ms by bot id=7510687058
2024-08-23 17:37:23,770 - INFO - Polling stopped
2024-08-23 17:37:24,029 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 17:37:26,920 - INFO - Run_Main
2024-08-23 17:37:26,921 - INFO - Starting
2024-08-23 17:37:26,921 - INFO - Start polling
2024-08-23 17:37:27,052 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 17:37:55,537 - INFO - Update id=142968476 is handled. Duration 172 ms by bot id=7510687058
2024-08-23 17:37:57,701 - INFO - Update id=142968477 is handled. Duration 233 ms by bot id=7510687058
2024-08-23 17:38:36,628 - INFO - Update id=142968478 is handled. Duration 156 ms by bot id=7510687058
2024-08-23 17:38:41,097 - INFO - Polling stopped
2024-08-23 17:38:41,354 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 17:38:45,187 - INFO - Run_Main
2024-08-23 17:38:45,188 - INFO - Starting
2024-08-23 17:38:45,188 - INFO - Start polling
2024-08-23 17:38:45,326 - INFO - Run polling for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
2024-08-23 17:38:50,366 - INFO - Update id=142968479 is handled. Duration 500 ms by bot id=7510687058
2024-08-23 17:49:41,747 - INFO - Polling stopped
2024-08-23 17:49:42,004 - INFO - Polling stopped for bot @async_hajil_bot id=7510687058 - 'bot_prototype'
